name: migu

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.0

      - name: Run Python script
        run: |
          python mg.py

      - name: Commit changes
        run: |
          git config --global user.email your@email.com
          git config --global user.name Your Name
          git add .
          git commit -m "Run daily Python script"
          git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
